image:
  upstreamtag: v0.9.2
  kubeconfigwriter: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter
  credsinit: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init
  gitinit: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init
  controller: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
  webhook: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
  entrypoint: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint
  pullrequest: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init
  imagedigestexporter: github.com/tektoncd/pipeline/cmd/imagedigestexporter
  gcsfetcher: gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher
auth:
  git:
    username:
    password:
    url: https://github.com
  docker:
    username:
    password:
    url: https://index.docker.io/v1/
    # url: https://gcr.io

webhook:
  enabled: true

rbac:
  cluster: true

pvc:
  size: 5Gi
