image:
  upstreamtag: v0.9.2-for-jx
  kubeconfigwriter: gcr.io/abayer-pipeline-crd/tekton-for-jx/kubeconfigwriter
  credsinit: gcr.io/abayer-pipeline-crd/tekton-for-jx/creds-init
  gitinit: gcr.io/abayer-pipeline-crd/tekton-for-jx/git-init
  controller: gcr.io/abayer-pipeline-crd/tekton-for-jx/controller
  webhook: gcr.io/abayer-pipeline-crd/tekton-for-jx/webhook
  entrypoint: gcr.io/abayer-pipeline-crd/tekton-for-jx/entrypoint
  pullrequest: gcr.io/abayer-pipeline-crd/tekton-for-jx/pullrequest-init
  imagedigestexporter: gcr.io/abayer-pipeline-crd/tekton-for-jx/imagedigestexporter
  gcsfetcher: gcr.io/abayer-pipeline-crd/tekton-for-jx/gcs-fetcher
auth:
  git:
    username:
    password:
    url: https://github.com
  docker:
    username:
    password:
    url: https://index.docker.io/v1/
    # url: https://gcr.io

webhook:
  enabled: true

rbac:
  cluster: true

pvc:
  size: 5Gi
